# action.yml
name: 'Gateway Conformance Tests: Extract Fixtures'
description: 'Extracts the fixtures from the Gateway Conformance Tests'
inputs:
  output:
    description: 'The path where the test fixtures should be extracted.'
    required: true
    default: 'fixtures'
  merged:
    description: 'Whether the fixtures should be merged into a single CAR file.'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - id: github
      uses: laurentsenta/docker-container-action/.github/actions/github@main
    - name: Extract the fixtures
      uses: laurentsenta/docker-container-action@main
      env:
        OUTPUT: ${{ inputs.output }}
        MERGED: ${{ inputs.merged }}
      with:
        repository: ${{ steps.github.outputs.action_repository }}
        ref: ${{ steps.github.outputs.action_sha || steps.github.outputs.action_ref }}
        dockerfile: Dockerfile
        args: extract-fixtures --directory="$OUTPUT" --merged="$MERGED"
        build-args: --build-arg VERSION=${{ steps.github.outputs.action_ref }}
